import type { Metadata } from "next";
import "./globals.css";
import { TopNav } from "./components/dashboard";
import { dm_sans } from "./fonts";

export const metadata: Metadata = {
  title: {
    template: '%s | SwiftCart',
    default: 'SwiftCart', // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} antialiased`}>
        <div className="min-h-screen w-full bg-[#f4f4f2]">
          <div className="w-full">
            <TopNav />
          </div>

          <div className="p-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
